const products = [
  {
    id: 1,
    title: 'Caixa Convite para Padrinhos de Casamento',
    slug: 'caixa-convite-para-padrinhos-de-casamento',
    description: 'Caixa personalizada para Padrinhos de Casamento.',
    image: '/images/caixa-convite-para-padrinhos-de-casamento.jpg',
    price: 8.95,
    category: 'Presentes e embalagens',
  },
  {
    id: 2,
    title: 'Manual dos padrinhos',
    slug: 'manual-dos-padrinhos',
    description: 'Manual dos Padrinhos',
    image: '/images/manual-dos-padrinhos.jpg',
    price: 4.0,
    category: 'Cartas e envelopes',
  },
  {
    id: 3,
    title: 'Convite Individual 10 Unidades',
    slug: 'convite-individual-10-unidades',
    description: 'Convite Individual 10 Unidades',
    image: '/images/convite-individual-10-unidades.jpg',
    price: 1.5,
    category: 'Cartas e envelopes',
  },
  {
    id: 4,
    title: 'Convite Casamento Rústico 10 unidades',
    slug: 'convite-casamento-rustico-10-unidades',
    description: 'Convite Casamento Rústico',
    image: '/images/convite-casamento-rustico-10-unidades.jpg',
    price: 32.0,
    category: 'Cartas e envelopes',
  },
  {
    id: 5,
    title: 'Convite para Padrinhos de Batismo',
    slug: 'convite-para-padrinhos-de-batismo',
    description: 'Lindo convite livro para padrinhos de batizado.',
    image: '/images/convite-para-padrinhos-de-batismo.jpg',
    price: 27.3,
    category: 'Artigos de festa',
  },
  {
    id: 6,
    title: 'Convite Floral (10 un) com papel vegetal',
    slug: 'convite-floral-10-unidades-com-papel-vegetal',
    description: 'Convite com papel translúcido',
    image: '/images/convite-floral-10-unidades-com-papel-vegetal.jpg',
    price: 59.0,
    category: 'Cartas e envelopes',
  },
  {
    id: 7,
    title: 'Mini Calendário de Mesa - Personalizado',
    slug: 'mini-calendario-de-mesa-personalizado',
    description: 'Kit calendário de Mesa',
    image: '/images/mini-calendario-de-mesa-personalizado.jpg',
    price: 20.0,
    category: 'Calendários',
  },
  {
    id: 8,
    title: 'Caneca Vovó é mãe com açúcar',
    slug: 'caneca-vovo-e-mae-com-acucar',
    description: 'Linda caneca - Vovó é mãe com açúcar',
    image: '/images/caneca-vovo-e-mae-com-acucar.jpg',
    price: 30.0,
    category: 'Copos e canecas',
  },
  {
    id: 9,
    title: 'Canecas - Pais dos Noivos',
    slug: 'canecas-pais-dos-noivos',
    description: '02 canecas para presentear os pais dos noivos.',
    image: '/images/canecas-pais-dos-noivos.jpg',
    price: 40.0,
    category: 'Copo e canecas',
  },
  {
    id: 10,
    title: 'Caneca Padrinhos de Batizado',
    slug: 'caneca-padrinhos-de-batizado',
    description: 'Canecas de Porcelana para padrinhos de batizado.',
    image: '/images/caneca-padrinhos-de-batizado.jpg',
    price: 20.0,
    category: 'Copo e canecas',
  },
];

export default products;
